-- ============================================================================
-- SUPERSEDED / NO-OP
-- ============================================================================
-- Substituída por 20260421181831_fe7b8d2f-3a01-4981-9533-83053eb41ab2.sql (e
-- pela 20260421181926 para a constraint UNIQUE), que criam fontes_receita e
-- planejamento_categorias com o schema que está VIVO em produção:
--   fontes_receita        -> coluna `nome` (não `descricao`), `updated_at`
--   planejamento_categorias -> `categoria_id` + `categoria_nome` (não `categoria`)
-- A versão original aqui criava schemas divergentes que nunca chegaram a valer
-- em produção — confirmado pelo types.ts gerado a partir do banco real.
--
-- Mantida como no-op (em vez de deletada) para preservar o nome do arquivo no
-- histórico de migrations e evitar que um `db reset` rode os CREATE TABLE
-- antigos e faça a 20260421 falhar com "relation already exists".
--
-- NÃO reintroduzir CREATE TABLE aqui — o schema canônico vive na 20260421181831.
