-- ============================================================================
-- SUPERSEDED / NO-OP
-- ============================================================================
-- Substituída por 20260421181831_fe7b8d2f-3a01-4981-9533-83053eb41ab2.sql, que
-- cria contas_pagar_receber com o schema que está VIVO em produção (colunas:
-- data_vencimento nullable, categoria, updated_at; tipo sem CHECK). A versão
-- original aqui criava um schema divergente (vencimento NOT NULL, tipo com
-- CHECK, sem categoria) que nunca chegou a valer em produção — confirmado pelo
-- types.ts gerado a partir do banco real.
--
-- Mantida como no-op (em vez de deletada) para preservar o nome do arquivo no
-- histórico de migrations e evitar que um `db reset` rode o CREATE TABLE antigo
-- e faça a 20260421 falhar com "relation already exists".
--
-- NÃO reintroduzir CREATE TABLE aqui — o schema canônico vive na 20260421181831.
